/**
 * Checks if the LLM's guess is correct regardless of case
 *
 * @param guess The string response generated by the LLM
 * @param answer The correct answer to the current drawing prompt
 * @returns {boolean} Returns True if answer is found in guess, False otherwise
 */

// TODO: Add substring filtering for correct answer
// For instance right now if the correct answer was Java and the LLM spit out Javascript it would pass when it should fail
export const checkGuess = (guess: string, answer: string): boolean => {
  return guess.toLowerCase().includes(answer.toLowerCase());
};
