import { PromptCategory } from "./types";

type Prompt = { name: string; category: PromptCategory };

export const DRAWING_PROMPTS: Prompt[] = [
  // Animals s
  { name: "Cat", category: PromptCategory.Animals },
  { name: "Dog", category: PromptCategory.Animals },
  { name: "Fish", category: PromptCategory.Animals },
  { name: "Bird", category: PromptCategory.Animals },
  { name: "Snake", category: PromptCategory.Animals },
  { name: "Lion", category: PromptCategory.Animals },
  { name: "Mouse", category: PromptCategory.Animals },
  { name: "Elephant", category: PromptCategory.Animals },
  { name: "Giraffe", category: PromptCategory.Animals },
  { name: "Butterfly", category: PromptCategory.Animals },
  { name: "Turtle", category: PromptCategory.Animals },
  { name: "Frog", category: PromptCategory.Animals },
  { name: "Bee", category: PromptCategory.Animals },
  { name: "Pig", category: PromptCategory.Animals },
  { name: "Horse", category: PromptCategory.Animals },

  // Food & Drink
  { name: "Apple", category: PromptCategory.Food },
  { name: "Banana", category: PromptCategory.Food },
  { name: "Pizza", category: PromptCategory.Food },
  { name: "Burger", category: PromptCategory.Food },
  { name: "Ice Cream Cone", category: PromptCategory.Food },
  { name: "Donut", category: PromptCategory.Food },
  { name: "Carrot", category: PromptCategory.Food },
  { name: "Coffee Cup", category: PromptCategory.Food },
  { name: "Cookie", category: PromptCategory.Food },
  { name: "Egg", category: PromptCategory.Food },
  { name: "Bread", category: PromptCategory.Food },
  { name: "Cheese", category: PromptCategory.Food },
  { name: "Hot Dog", category: PromptCategory.Food },
  { name: "Grapes", category: PromptCategory.Food },
  { name: "Watermelon", category: PromptCategory.Food },

  // Household Objects -> Objects
  { name: "House", category: PromptCategory.Objects },
  { name: "Chair", category: PromptCategory.Objects },
  { name: "Table", category: PromptCategory.Objects },
  { name: "Key", category: PromptCategory.Objects },
  { name: "Bed", category: PromptCategory.Objects },
  { name: "Lamp", category: PromptCategory.Objects },
  { name: "Door", category: PromptCategory.Objects },
  { name: "Book", category: PromptCategory.Objects },
  { name: "Scissors", category: PromptCategory.Objects },
  { name: "Clock", category: PromptCategory.Objects },
  { name: "Spoon", category: PromptCategory.Objects },
  { name: "Fork", category: PromptCategory.Objects },
  { name: "Television", category: PromptCategory.Objects },
  { name: "Sofa", category: PromptCategory.Objects },
  { name: "Lightbulb", category: PromptCategory.Objects },

  // Nature -> Nature
  { name: "Tree", category: PromptCategory.Nature },
  { name: "Sun", category: PromptCategory.Nature },
  { name: "Moon", category: PromptCategory.Nature },
  { name: "Star", category: PromptCategory.Nature },
  { name: "Cloud", category: PromptCategory.Nature },
  { name: "Flower", category: PromptCategory.Nature },
  { name: "Mountain", category: PromptCategory.Nature },
  { name: "Rainbow", category: PromptCategory.Nature },
  { name: "Lightning Bolt", category: PromptCategory.Nature },
  { name: "Leaf", category: PromptCategory.Nature },
  { name: "Volcano", category: PromptCategory.Nature },
  { name: "River", category: PromptCategory.Nature },
  { name: "Snowflake", category: PromptCategory.Nature },
  { name: "Mushroom", category: PromptCategory.Nature },
  { name: "Wave", category: PromptCategory.Nature },

  // Transportation -> Objects
  { name: "Car", category: PromptCategory.Objects },
  { name: "Bicycle", category: PromptCategory.Objects },
  { name: "Boat", category: PromptCategory.Objects },
  { name: "Airplane", category: PromptCategory.Objects },
  { name: "Train", category: PromptCategory.Objects },
  { name: "Bus", category: PromptCategory.Objects },
  { name: "Helicopter", category: PromptCategory.Objects },
  { name: "Rocket", category: PromptCategory.Objects },
  { name: "Motorcycle", category: PromptCategory.Objects },
  { name: "Sailboat", category: PromptCategory.Objects },

  // Clothing -> Objects
  { name: "Hat", category: PromptCategory.Objects },
  { name: "T-shirt", category: PromptCategory.Objects },
  { name: "Sock", category: PromptCategory.Objects },
  { name: "Shoe", category: PromptCategory.Objects },
  { name: "Pants", category: PromptCategory.Objects },
  { name: "Dress", category: PromptCategory.Objects },
  { name: "Glasses", category: PromptCategory.Objects },
  { name: "Watch", category: PromptCategory.Objects },
  { name: "Scarf", category: PromptCategory.Objects },
  { name: "Glove", category: PromptCategory.Objects },

  // Miscellaneous -> Objects
  { name: "Heart", category: PromptCategory.Objects },
  { name: "Smiley Face", category: PromptCategory.Objects },
  { name: "Guitar", category: PromptCategory.Objects },
  { name: "Computer", category: PromptCategory.Objects },
  { name: "Bridge", category: PromptCategory.Objects },
  { name: "Sword", category: PromptCategory.Objects },
  { name: "Shield", category: PromptCategory.Objects },
  { name: "Crown", category: PromptCategory.Objects },
  { name: "Money Bag", category: PromptCategory.Objects },
  { name: "Ghost", category: PromptCategory.Objects },
];
